language: swift
osx_image: xcode11.3
xcode_project: iina.xcodeproj

# Build the main app, which happens to depend on the other two targets.
script: xcodebuild -project iina.xcodeproj -scheme iina CODE_SIGNING_ALLOWED=NO

notifications:
  email: false
